#!/bin/bash

# Install/remove software
sudo pamac update --no-confirm
sudo pamac install perl-anyevent-i3 alacritty neovim firefox thunar manjaro-pulse pa-applet pavucontrol discord stow postgresql --no-confirm
sudo pamac build nordic-theme --no-confirm
sudo pamac remove -o vim palemoon pcmanfm --no-confirm


# Use stow to create symlinks
stow */ -t ~


# Change shell to zsh
sudo chsh -s /bin/zsh 
sudo chsh -s /bin/zsh $USER


# Reboot 
reboot 
