#!/bin/bash

i3-msg "workspace 7; append_layout $HOME/.i3/workspace-7.json" 
alacritty --class Alacritty,term1 &
alacritty --class Alacritty,term2 &
alacritty --class Alacritty,term3 &
alacritty --class Alacritty,term4 &
